org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.java.home=C:/tools/java_home/jdk21
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
org.gradle.caching=true
systemProp.org.gradle.internal.http.connectionTimeout=60000
systemProp.org.gradle.internal.http.socketTimeout=180000
